alert("In this experiment we will measure your response time. You will be shown a series of simple math equations. Answer these equations as quickly and accurately as you can.");
let start = Date.now();
let answer1 = prompt("What is 1 + 2?");
let end = Date.now();
let responseTime = (end - start) / 1000;
alert("You answered " + answer1 + " in " + responseTime + " seconds");
start = Date.now();
let answer2 = prompt("What is 1 + 3?");
end = Date.now();
responseTime = (end - start) / 1000;
alert("You answered " + answer2 + " in " + responseTime + " seconds");
start = Date.now();
let answer3 = prompt("What is 1 + 4?");
end = Date.now();
responseTime = (end - start) / 1000;
alert("You answered " + answer3 + " in " + responseTime + " seconds");
alert("Thank you for your participation!");