/* alert("In this experiment we will measure your response time. You will be shown a series of simple math equations. Answer these equations as quickly and accurately as you can.");
let math1 = Math.floor(Math.random() * 10) + 1;
let math2 = Math.floor(Math.random() * 10) + 1;
let start = Date.now();
let answer1 = prompt("What is " + math1 + " + " + math2 + "?");
let end = Date.now();
let responseTime = (end - start) / 1000;
alert("You answered " + answer1 + " in " + responseTime + " seconds");
math1 = Math.floor(Math.random() * 10) + 1;
math2 = Math.floor(Math.random() * 10) + 1;
start = Date.now();
let answer2 = prompt("What is " + math1 + " + " + math2 + "?");
end = Date.now();
responseTime = (end - start) / 1000;
alert("You answered " + answer2 + " in " + responseTime + " seconds");
math1 = Math.floor(Math.random() * 10) + 1;
math2 = Math.floor(Math.random() * 10) + 1;
start = Date.now();
let answer3 = prompt("What is " + math1 + " + " + math2 + "?");
end = Date.now();
responseTime = (end - start) / 1000;
alert("You answered " + answer3 + " in " + responseTime + " seconds");
alert("Thank you for your participation!");
 */